model_list:
  - model_name: deepseek/deepseek-chat
    litellm_params:
      model: deepseek/deepseek-chat
      api_key: "os.environ/OPENAI_API_KEY"

router_settings:
  routing_strategy: simple-shuffle
  num_retries: 2
